import mock

raise Exception("error")